export const GET_RIDE_BOOKING_ORDER = "GET_RIDE_BOOKING_ORDER";
export const GET_RIDE_BOOKING_ORDER_REQUEST = "GET_RIDE_BOOKING_ORDER_REQUEST";
export const GET_CURRENT_DRIVER_LOCATION = "GET_CURRENT_DRIVER_LOCATION";