export const GET_ALL_DRIVERS_REQUEST = "GET_ALL_DRIVERS_REQUEST";
export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
export const SET_RIDE_TO_LOCALSTOREAGE = "SET_RIDE_TO_LOCALSTORE";
export const GET_RIDE_CONFIRMATION_DETAILS = "GET_RIDE_CONFIRMATION_DETAILS";
export const GET_USER_CURRENT_lOCATION = "GET_USER_CURRENT_lOCATION";
export const GET_RIDE_BOOKING_STATUS = "GET_RIDE_BOOKING_STATUS";
export const GET_DRIVER_POSITION_INFO = "GET_DRIVER_POSITION_INFO";